FROM jdeathe/centos-ssh:2.6.1
RUN curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
RUN yum -y install nodejs
RUN npm install pm2 -g

CMD /usr/bin/supervisord --configuration=/etc/supervisord.conf