- hosts: app1
  become: yes
  become_method: sudo
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /usr/www
        state: directory
        mode: '0755'
    - name: Copy application
      copy:
        src: ./files/server.js
        dest: /usr/www/server.js
        mode: '0644'
    - name: Start application
      command: pm2 restart server
      args:
        chdir: /usr/www/