- hosts: app
  become: yes
  become_method: sudo
  # 逐步升级
  # serial: "50%"
  tasks:
    - name: Copy rollback shell
      copy:
        src: ./files/getRollbackFolder.sh
        dest: /usr/www/getRollbackFolder.sh
        mode: '0644'
    - name: chmod +x shell
      command: chmod +x ./getRollbackFolder.sh
      args:
        chdir: /usr/www/
    - name: Get rollback folder name
      command: ./getRollbackFolder.sh
      register: rollback
      args:
        chdir: /usr/www/
    - name: Stop application
      command: pm2 delete server
      ignore_errors: yes
    - name: Start application {{ rollback.stdout }}
      command: pm2 start server.js --name server
      args:
        chdir: /usr/www/{{ rollback.stdout }}