- hosts: app
  become: yes
  become_method: sudo
  tasks:
    - name: Copy install.sh to remote $HOME
      copy:
        src: ./test/install.sh
        dest: /home/app-admin/install.sh
        mode: '0644'
    - name: chmod
      shell: >
        chmod +x ./install.sh
      args:
        executable: /bin/bash
        chdir: "/home/app-admin"
    - name: "Install nvm"
      shell: >
        . /home/app-admin/install.sh
      args:
        executable: /bin/bash
        chdir: "/home/app-admin"
        creates: "/home/app-admin/.nvm/nvm.sh"  
    - name: chmod
      shell: >
        chmod +x /home/app-admin/.nvm/nvm.sh
      args:
        executable: /bin/bash
        chdir: "/home/app-admin"
    - name: "Install node"
      shell: >
        . /home/app-admin/.nvm/nvm.sh && nvm install 10.16.3
      args:
        executable: /bin/bash
        chdir: "/home/app-admin"
        creates: "/home/app-admin/.nvm/versions/10.16.3"