FROM jdeathe/centos-ssh:2.6.1
RUN yum -y install wget
RUN wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum -y upgrade
RUN yum install -y initscripts
RUN yum -y install ansible
RUN yum -y install jenkins java-1.8.0-openjdk-devel

CMD bash -c "/etc/rc.d/init.d/jenkins start && /usr/bin/supervisord --configuration=/etc/supervisord.conf"